services:
  db:
    image: mysql:8.0
    container_name: ecommerce_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - "MYSQL_DATABASE=ecommerce_db"
      - "MYSQL_ROOT_PASSWORD=digital"
      - "MYSQL_ROOT_HOST=%"
    ports:
      - "3306:3306"
  redis:
    image: redis:alpine
    container_name: ecommerce_redis
    ports:
      - "6379:6379"
  web:
    build: .
    container_name: ecommerce_web
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - "DATABASE_URL=mysql+pymysql://root:digital@db:3306/ecommerce_db"
      - "CELERY_BROKER_URL=redis://redis:6379/0"
      - "CELERY_RESULT_BACKEND=redis://redis:6379/0"
    depends_on:
      - db
      - redis
  worker:
    build: .
    container_name: ecommerce_worker
    command: celery -A worker.app worker --loglevel=info
    environment:
      - "DATABASE_URL=mysql+pymysql://root:digital@db:3306/ecommerce_db"
      - "CELERY_BROKER_URL=redis://redis:6379/0"
      - "CELERY_RESULT_BACKEND=redis://redis:6379/0" 
    depends_on:
      - db
      - redis
